api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        # pagination
        # let clients choose if they want pagination
        pagination_client_enabled: true
        # default number of items per page
        # pagination_items_per_page: 15 # default 30
        # let clients choose the number of items per page
        pagination_client_items_per_page: true
    formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
        # html: ["text/html"]
    # patch_formats:
    #     json: ["application/merge-patch+json"]
    #     jsonapi: ["application/vnd.api+json"]

    swagger:
        swagger_ui_extra_configuration:
            docExpansion: none
            persistAuthorization: true
            filter: true
