---
name: "web2mp3_v2_api"

networks:
  net:
    name: "webapps"
    external: true

services:
  web2mp3_v2_api:
    env_file:
    - path: ./.env
      required: true
    - path: ./.env.local
      required: false
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, web2mp3_v2_api:80
      CADDY_SERVER_NAME: ${CADDY_SERVER_NAME:?}
      # DEFAULT_URI: https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}
      DEFAULT_URI: ${DEFAULT_URI:-localhost}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      # DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://web2mp3_v2_api/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # MERCURE_EXTRA_DIRECTIVES: "cors_origins http://debian-server:4200 https://web2mp3-v2.100.124.238.99.nip.io"
      # MERCURE_CORS: "cors_origins http://debian-server:4200 https://web2mp3-v2.100.124.238.99.nip.io"
      # MERCURE_CORS: "cors_origins ${MERCURE_CORS_ORIGINS:?}"
    user: "${UID:?}:${GID:?}"
    networks:
    - "net"
    volumes:
    # - caddy_data:/data
    # - caddy_config:/config
    - "/srv/docker_data/web2mp3_v2/caddy_data:/data"
    - "/srv/docker_data/web2mp3_v2/caddy_config:/config"
    - "/srv/docker_data/web2mp3_v2/database:/app/database"
    - "/srv/docker_data/web2mp3_v2/storage:/app/public/storage"
    # restart: unless-stopped

  web2mp3_v2_workers:
    env_file:
    - path: "./.env"
      required: true
    - path: "./.env.local"
      required: false
    user: "${UID:?}:${GID:?}"
    networks:
    - "net"
    volumes:
    # - "./php.ini:/usr/local/etc/php/php.ini"
    - "./queue_worker.conf:/etc/supervisor/conf.d/queue_worker.conf:ro"
    - "/srv/docker_data/web2mp3_v2/database:/app/database"
    - "/srv/docker_data/web2mp3_v2/storage:/app/public/storage"
    # restart: unless-stopped

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

# volumes:
#   caddy_data:
#   caddy_config:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
###> doctrine/doctrine-bundle ###
  # database_data:
###< doctrine/doctrine-bundle ###

###> doctrine/doctrine-bundle ###
  # database:
  #   image: postgres:${POSTGRES_VERSION:-16}-alpine
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB:-app}
  #     # You should definitely change the password in production
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
  #     POSTGRES_USER: ${POSTGRES_USER:-app}
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
  #     timeout: 5s
  #     retries: 5
  #     start_period: 60s
  #   volumes:
  #     - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
