[supervisord]
nodaemon=true
# pidfile=/var/run/supervisord.pid
pidfile=/tmp/supervisord.pid
# logfile=/var/www/storage/logs/supervisord.log
logfile=/app/var/log/supervisord.log

# # "default" queue
# [program:default-queue-worker]
# process_name=%(program_name)s_%(process_num)02d
# ; command=/usr/local/bin/php /var/www/artisan queue:work -v --sleep=3 --tries=3 --timeout=300
# ; command=/usr/local/bin/php /var/www/artisan queue:listen -v --sleep=3 --tries=3 --timeout=300
# command=/usr/local/bin/php /var/www/artisan queue:%(ENV_WORKER_MODE)s --queue=default -v --sleep=3 --tries=3 --timeout=300
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# numprocs=3
# redirect_stderr=true
# stdout_logfile=/dev/stdout
# ; prevent supervisor from trying to rotate the logs when using /dev/stdout
# stdout_logfile_maxbytes=0
# stopwaitsecs=600

# "default" queue
[program:default-queue-worker]
process_name=%(program_name)s_%(process_num)02d
# command=/usr/local/bin/php /var/www/artisan queue:%(ENV_WORKER_MODE)s --queue=downloads -v --timeout=600
command=php bin/console messenger:consume async_default -vv --time-limit=3600 --limit=50
startsecs=0
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=3
redirect_stderr=true
stdout_logfile=/dev/stdout
; prevent supervisor from trying to rotate the logs when using /dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=600

# "download" queue
[program:download-queue-worker]
process_name=%(program_name)s_%(process_num)02d
# command=/usr/local/bin/php /var/www/artisan queue:%(ENV_WORKER_MODE)s --queue=downloads -v --timeout=600
command=php bin/console messenger:consume async_download -vv --time-limit=3600 --limit=50
startsecs=0
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
; prevent supervisor from trying to rotate the logs when using /dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=600

# scheduler
[program:scheduler]
command=php bin/console messenger:consume scheduler_default -vv --time-limit=3600 --limit=50
startsecs=0
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
; prevent supervisor from trying to rotate the logs when using /dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=600
